<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.link' shared service.

return $this->services['tpay.link'] = \Tpay\Factory\ContextFactory::getLink();
