<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.order_history' shared service.

return $this->services['tpay.order_history'] = new \OrderHistory();
