<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxsgtem\legacyAppDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxsgtem/legacyAppDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCxsgtem.legacy');

    return;
}

if (!\class_exists(legacyAppDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCxsgtem\legacyAppDevDebugProjectContainer::class, legacyAppDevDebugProjectContainer::class, false);
}

return new \ContainerCxsgtem\legacyAppDevDebugProjectContainer([
    'container.build_hash' => 'Cxsgtem',
    'container.build_id' => '21a0a28b',
    'container.build_time' => 1709634606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxsgtem');
