<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjkkhfc\legacyAppProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjkkhfc/legacyAppProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXjkkhfc.legacy');

    return;
}

if (!\class_exists(legacyAppProdProjectContainer::class, false)) {
    \class_alias(\ContainerXjkkhfc\legacyAppProdProjectContainer::class, legacyAppProdProjectContainer::class, false);
}

return new \ContainerXjkkhfc\legacyAppProdProjectContainer([
    'container.build_hash' => 'Xjkkhfc',
    'container.build_id' => '682d21ce',
    'container.build_time' => 1700482460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjkkhfc');
