<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.language' shared service.

return $this->services['tpay.language'] = \Tpay\Factory\ContextFactory::getLanguage();
