<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.cart' shared service.

return $this->services['tpay.cart'] = \Tpay\Factory\ContextFactory::getCart();
