<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.service.transaction' shared service.

return $this->services['tpay.service.transaction'] = new \Tpay\Service\TransactionService(${($_ = isset($this->services['tpay.cart']) ? $this->services['tpay.cart'] : $this->load('getTpay_CartService.php')) && false ?: '_'}, ${($_ = isset($this->services['tpay.repository.transaction']) ? $this->services['tpay.repository.transaction'] : $this->load('getTpay_Repository_TransactionService.php')) && false ?: '_'}, ${($_ = isset($this->services['tpay.service.surcharge']) ? $this->services['tpay.service.surcharge'] : ($this->services['tpay.service.surcharge'] = new \Tpay\Service\SurchargeService())) && false ?: '_'}, ${($_ = isset($this->services['tpay.context']) ? $this->services['tpay.context'] : $this->load('getTpay_ContextService.php')) && false ?: '_'});
