<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.handler.order_status_handler' shared service.

return $this->services['tpay.handler.order_status_handler'] = new \Tpay\Handler\OrderStatusHandler(${($_ = isset($this->services['tpay.order_history']) ? $this->services['tpay.order_history'] : ($this->services['tpay.order_history'] = new \OrderHistory())) && false ?: '_'}, ${($_ = isset($this->services['tpay.repository.transaction']) ? $this->services['tpay.repository.transaction'] : $this->load('getTpay_Repository_TransactionService.php')) && false ?: '_'});
