<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tpay.handler.install_query_handler' shared service.

return $this->services['tpay.handler.install_query_handler'] = new \Tpay\Handler\InstallQueryHandler();
