<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.util.secret_hash' shared service.

return $this->services['tpay.util.secret_hash'] = \Tpay\Util\SecretHash::getHash('6G5XKA0FjOP03LLtNj7p0hff4L7G8aiRSqCwEOhK3WOjaQLzC8qR7p30wxy8mx9o');
