<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.smarty' shared service.

return $this->services['tpay.smarty'] = \Tpay\Factory\ContextFactory::getSmarty();
