<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.service.card_service' shared service.

return $this->services['tpay.service.card_service'] = new \Tpay\Service\CardService(${($_ = isset($this->services['tpay.repository.credit_card']) ? $this->services['tpay.repository.credit_card'] : $this->load('getTpay_Repository_CreditCardService.php')) && false ?: '_'});
