<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.currency' shared service.

return $this->services['tpay.currency'] = \Tpay\Factory\ContextFactory::getCurrency();
