<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tpay.controller' shared service.

return $this->services['tpay.controller'] = \Tpay\Factory\ContextFactory::getController();
